backend:
  name: git-gateway
  branch: main # or master

media_folder: "assets/images" # where photos go
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts" # It will save her posts in a folder called /posts/
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
