backend:
  name: git-gateway
  repo: rc072406/annarichman 
  branch: main
  base_url: https://api.netlify.com # The bridge
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts" # It will save new posts here
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
